spring:
    config:
        activate:
            on-profile: dev
    data:
        redis:
            database: 3
            host: 127.0.0.1
            port: 6379
    datasource:
        master:
            hikari:
                auto-commit: true
                connection-test-query: SELECT 1
                connection-timeout: 30000
                idle-timeout: 300000
                max-lifetime: 1800000
                maximum-pool-size: 30
                minimum-idle: 5
                pool-name: CordysMasterHikariCP
            password: root
            url: jdbc:mysql://127.0.0.1:3309/crm_master?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
            username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3309/crm_tenant_default?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
        username: root
    freemarker:
        check-template-location: false
    groovy:
        template:
            check-template-location: false
    session:
        redis:
            repository-type: indexed
        timeout: 43200s

cordys:
    tenant:
        provision:
            drop-database-on-failure: true

dashboard:
    whitelist:
        allowed: ''
        enabled: false

logback:
    root:
        level: INFO

logger:
    sql:
        level: info

logging:
    config: classpath:logback-spring.xml
    file:
        path: D:\workSpace\CordysCRM\logs\cordys-crm
    level:
        com:
            zaxxer:
                hikari: INFO
        org:
            apache:
                ibatis: INFO
            mybatis: INFO
            springframework: INFO

management:
    endpoints:
        enabled-by-default: false

mysql:
    embedded:
        enabled: true

redis:
    embedded:
        enabled: true

mmba:
    api-base-url: https://120.26.9.2:9074
    app-key: 1_01b0d6f7624fd7ee59899893c75f83e1
    company-code: YMFTEST
    secret: e333e60912e8a11cee384586afe780af
    filepath: /mmba/file/
