package cn.cordys.mmba.domain;

import cn.cordys.common.domain.BaseModel;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Table(name = "mmba_command_result")
public class MmbaCommandResult extends BaseModel {
    private String tenantId;
    private String tenancyName;
    private Integer behaviorType;
    private Long appId;
    private String appName;
    private String createTimeText;
    private Long timestampValue;
    private Long insertTimeValue;
    private String reqId;
    private String traceId;
    private String um;
    private String staffIdInApp;
    private String staffImAppAccount;
    private String staffImNickName;
    private String staffImAppHeaderPic;
    private String staffMobile;
    private String staffArea;
    private String staffSex;
    private String staffName;
    private String orgName;
    private String orgNames;
    private Long deptId;
    private String deptIdPath;
    private String deptInfo;
    private String company;
    private String region;
    private String department;
    private String deviceId;
    private String deviceName;
    private String appPkgName;
    private String imei;
    private String imei2;
    private String targetType;
    private String targetValue;
    private String customer;
    private String customerAccount;
    private String customerAccountId;
    private String customerNickname;
    private String customerPic;
    private String customerTel;
    private String friendPhone;
    private String contactImIdInApp;
    private String contactImAppAccount;
    private String contactImAppNickName;
    private String contactImAppNote;
    private String contactDescription;
    private String contactImAppHeaderPic;
    private String contactMobile;
    private String contactArea;
    private String contactSex;
    private String contactWeixinTags;
    private String isFriend;
    private Integer operFlag;
    private String source;
    private String wxType;
    private String friendSearch;
    private String groupId;
    private String groupName;
    private String memberAccount;
    private String memberNickName;
    private String memberPic;
    private String recId;
    private String umPhone;
    private String umWxid;
    private Integer msgType;
    private Integer chatType;
    private Integer msgStatus;
    private Integer processStatus;
    private Integer resultStatus;
    private String operateTime;
    private String bizExtInfo;
    private String rawData;
    private String callbackRecordId;
}
