CREATE TABLE IF NOT EXISTS mmba_request_record (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    req_id VARCHAR(64) NOT NULL COMMENT '请求唯一标识',
    trace_id VARCHAR(64) DEFAULT NULL COMMENT 'MMBA返回traceId',
    mmba_url VARCHAR(255) DEFAULT NULL COMMENT '请求URL',
    request_headers LONGTEXT COMMENT '请求头JSON',
    request_body LONGTEXT COMMENT '请求体JSON',
    response_body LONGTEXT COMMENT '响应体JSON',
    response_code INT DEFAULT NULL COMMENT '响应码',
    response_message VARCHAR(512) DEFAULT NULL COMMENT '响应消息',
    request_status VARCHAR(32) DEFAULT NULL COMMENT '请求状态',
    raw_result LONGTEXT COMMENT '完整响应内容',
    create_time BIGINT NOT NULL COMMENT '创建时间',
    create_user VARCHAR(32) NOT NULL COMMENT '创建人',
    update_time BIGINT NOT NULL COMMENT '更新时间',
    update_user VARCHAR(32) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_request_req_id (req_id),
    KEY idx_mmba_request_biz_time (biz_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA请求记录表';

CREATE TABLE IF NOT EXISTS mmba_callback_record (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    behavior_type INT NOT NULL COMMENT '回调类型',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT 'MMBA租户名',
    record_count INT NOT NULL DEFAULT 0 COMMENT 'data条数',
    payload_hash VARCHAR(64) DEFAULT NULL COMMENT '原始回调哈希',
    payload_raw LONGTEXT COMMENT '原始回调JSON',
    process_status VARCHAR(32) DEFAULT NULL COMMENT '处理状态',
    process_result VARCHAR(512) DEFAULT NULL COMMENT '处理结果',
    error_message TEXT COMMENT '错误信息',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    create_time BIGINT NOT NULL COMMENT '创建时间',
    create_user VARCHAR(32) NOT NULL COMMENT '创建人',
    update_time BIGINT NOT NULL COMMENT '更新时间',
    update_user VARCHAR(32) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    KEY idx_mmba_callback_behavior_time (behavior_type, create_time),
    KEY idx_mmba_callback_payload_hash (payload_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA回调原始记录表';

CREATE TABLE IF NOT EXISTS mmba_command_result (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    behavior_type INT NOT NULL COMMENT '回调类型',
    tenant_id VARCHAR(32) DEFAULT NULL COMMENT '租户ID',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT 'MMBA租户名',
    app_id BIGINT DEFAULT NULL COMMENT '应用ID',
    app_name VARCHAR(128) DEFAULT NULL COMMENT '应用名称',
    create_time_text VARCHAR(64) DEFAULT NULL COMMENT '业务时间文本',
    timestamp_value BIGINT DEFAULT NULL COMMENT '业务时间戳',
    insert_time_value BIGINT DEFAULT NULL COMMENT '入库时间戳',
    req_id VARCHAR(64) NOT NULL COMMENT '请求唯一标识',
    trace_id VARCHAR(64) DEFAULT NULL COMMENT '请求traceId',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户名',
    staff_id_in_app VARCHAR(128) DEFAULT NULL COMMENT '员工微信ID',
    staff_im_app_account VARCHAR(128) DEFAULT NULL COMMENT '员工微信账号',
    staff_im_nick_name VARCHAR(128) DEFAULT NULL COMMENT '员工微信昵称',
    staff_im_app_header_pic LONGTEXT COMMENT '员工微信头像',
    staff_mobile VARCHAR(32) DEFAULT NULL COMMENT '员工手机号',
    staff_area VARCHAR(255) DEFAULT NULL COMMENT '员工地区',
    staff_sex VARCHAR(32) DEFAULT NULL COMMENT '员工性别',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '员工名称',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '组织名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织路径',
    dept_id BIGINT DEFAULT NULL COMMENT '部门ID',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '部门路径',
    dept_info LONGTEXT COMMENT '部门信息JSON',
    company VARCHAR(255) DEFAULT NULL COMMENT '公司',
    region VARCHAR(255) DEFAULT NULL COMMENT '大区',
    department VARCHAR(255) DEFAULT NULL COMMENT '部门',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    device_name VARCHAR(128) DEFAULT NULL COMMENT '设备名称',
    app_pkg_name VARCHAR(128) DEFAULT NULL COMMENT '应用包名',
    imei VARCHAR(64) DEFAULT NULL COMMENT 'IMEI1',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT 'IMEI2',
    target_type VARCHAR(32) DEFAULT NULL COMMENT '目标类型',
    target_value VARCHAR(256) DEFAULT NULL COMMENT '目标值',
    customer VARCHAR(128) DEFAULT NULL COMMENT '联系人名称',
    customer_account VARCHAR(128) DEFAULT NULL COMMENT '客户微信号',
    customer_account_id VARCHAR(128) DEFAULT NULL COMMENT '客户微信ID',
    customer_nickname VARCHAR(128) DEFAULT NULL COMMENT '客户微信昵称',
    customer_pic LONGTEXT COMMENT '客户微信头像',
    customer_tel VARCHAR(32) DEFAULT NULL COMMENT '联系人电话',
    friend_phone VARCHAR(32) DEFAULT NULL COMMENT '好友手机号',
    contact_im_id_in_app VARCHAR(128) DEFAULT NULL COMMENT '好友微信ID',
    contact_im_app_account VARCHAR(128) DEFAULT NULL COMMENT '好友微信号',
    contact_im_app_nick_name VARCHAR(128) DEFAULT NULL COMMENT '好友微信昵称',
    contact_im_app_note VARCHAR(255) DEFAULT NULL COMMENT '好友备注',
    contact_description VARCHAR(512) DEFAULT NULL COMMENT '好友描述',
    contact_im_app_header_pic LONGTEXT COMMENT '好友头像',
    contact_mobile VARCHAR(255) DEFAULT NULL COMMENT '好友手机号',
    contact_area VARCHAR(255) DEFAULT NULL COMMENT '好友地区',
    contact_sex VARCHAR(32) DEFAULT NULL COMMENT '好友性别',
    contact_weixin_tags VARCHAR(255) DEFAULT NULL COMMENT '好友标签',
    is_friend VARCHAR(32) DEFAULT NULL COMMENT '好友类型',
    oper_flag INT DEFAULT NULL COMMENT '操作类型',
    source VARCHAR(32) DEFAULT NULL COMMENT '添加来源',
    wx_type VARCHAR(32) DEFAULT NULL COMMENT '添加方式',
    friend_search VARCHAR(255) DEFAULT NULL COMMENT '好友搜索内容',
    group_id VARCHAR(128) DEFAULT NULL COMMENT '群ID',
    group_name VARCHAR(255) DEFAULT NULL COMMENT '群名称',
    member_account VARCHAR(128) DEFAULT NULL COMMENT '群成员账号',
    member_nick_name VARCHAR(128) DEFAULT NULL COMMENT '群成员昵称',
    member_pic LONGTEXT COMMENT '群成员头像',
    rec_id VARCHAR(128) DEFAULT NULL COMMENT '消息接收对象ID',
    um_phone VARCHAR(32) DEFAULT NULL COMMENT '员工微信手机号',
    um_wxid VARCHAR(128) DEFAULT NULL COMMENT '员工微信ID',
    msg_type INT DEFAULT NULL COMMENT '消息类型',
    chat_type INT DEFAULT NULL COMMENT '聊天类型',
    msg_status INT DEFAULT NULL COMMENT '消息状态',
    process_status INT DEFAULT NULL COMMENT '处理状态',
    result_status INT DEFAULT NULL COMMENT '结果状态',
    operate_time VARCHAR(64) DEFAULT NULL COMMENT '操作时间',
    biz_ext_info LONGTEXT COMMENT '扩展信息',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    create_time BIGINT NOT NULL COMMENT '创建时间',
    create_user VARCHAR(32) NOT NULL COMMENT '创建人',
    update_time BIGINT NOT NULL COMMENT '更新时间',
    update_user VARCHAR(32) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_command_req_target (behavior_type, req_id, target_value),
    KEY idx_mmba_command_um_time (um, create_time),
    KEY idx_mmba_command_callback_id (callback_record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA统一指令结果表';

CREATE TABLE IF NOT EXISTS mmba_device (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    device_id VARCHAR(64) NOT NULL COMMENT '设备ID',
    device_name VARCHAR(128) DEFAULT NULL COMMENT '设备名称',
    device_type VARCHAR(128) DEFAULT NULL COMMENT '设备型号',
    device_status INT DEFAULT NULL COMMENT '设备状态',
    imei VARCHAR(64) DEFAULT NULL COMMENT 'IMEI1',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT 'IMEI2',
    iccid VARCHAR(64) DEFAULT NULL COMMENT 'ICCID1',
    iccid2 VARCHAR(64) DEFAULT NULL COMMENT 'ICCID2',
    phone VARCHAR(32) DEFAULT NULL COMMENT '手机号1',
    phone2 VARCHAR(32) DEFAULT NULL COMMENT '手机号2',
    telecom_operators VARCHAR(64) DEFAULT NULL COMMENT '运营商1',
    telecom_operators2 VARCHAR(64) DEFAULT NULL COMMENT '运营商2',
    um VARCHAR(128) DEFAULT NULL COMMENT '当前员工',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '员工名称',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '组织名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织路径',
    last_behavior_type INT DEFAULT NULL COMMENT '最近一次设备类回调类型',
    last_audit_time BIGINT DEFAULT NULL COMMENT '最近审计时间',
    raw_data LONGTEXT COMMENT '最近一次设备原始JSON',
    create_time BIGINT NOT NULL COMMENT '创建时间',
    create_user VARCHAR(32) NOT NULL COMMENT '创建人',
    update_time BIGINT NOT NULL COMMENT '更新时间',
    update_user VARCHAR(32) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_device_device_id (device_id),
    KEY idx_mmba_device_imei (imei),
    KEY idx_mmba_device_um (um)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA设备主表';

CREATE TABLE IF NOT EXISTS mmba_device_mapping (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户名',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '员工名称',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    imei VARCHAR(64) DEFAULT NULL COMMENT 'IMEI',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT 'IMEI2',
    iccid VARCHAR(64) DEFAULT NULL COMMENT 'ICCID',
    wxid VARCHAR(128) DEFAULT NULL COMMENT '微信ID',
    wx_account VARCHAR(128) DEFAULT NULL COMMENT '微信账号',
    wx_phone VARCHAR(32) DEFAULT NULL COMMENT '微信手机号',
    wx_nick_name VARCHAR(128) DEFAULT NULL COMMENT '微信昵称',
    wx_header_pic TEXT COMMENT '微信头像',
    qq VARCHAR(64) DEFAULT NULL COMMENT '微信绑定QQ',
    mapping_status VARCHAR(32) DEFAULT NULL COMMENT '映射状态',
    last_sync_time BIGINT DEFAULT NULL COMMENT '最后同步时间',
    raw_data LONGTEXT COMMENT '最近一次映射来源JSON',
    create_time BIGINT NOT NULL COMMENT '创建时间',
    create_user VARCHAR(32) NOT NULL COMMENT '创建人',
    update_time BIGINT NOT NULL COMMENT '更新时间',
    update_user VARCHAR(32) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_device_mapping (um, wxid),
    KEY idx_mmba_device_mapping_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA设备映射表';

CREATE TABLE IF NOT EXISTS mmba_call_record_audit (
    es_id VARCHAR(64) NOT NULL COMMENT '通话记录的唯一标识',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    answer_time VARCHAR(32) DEFAULT NULL COMMENT '电话接通时间',
    answer_timestamp BIGINT DEFAULT NULL COMMENT '电话接通时间戳',
    begin_time VARCHAR(32) DEFAULT NULL COMMENT '电话拨打时间',
    begin_timestamp BIGINT DEFAULT NULL COMMENT '拨打时间戳',
    biz_ext_info LONGTEXT COMMENT '扩展字段',
    call_status VARCHAR(32) DEFAULT NULL COMMENT '通话状态',
    call_type INT DEFAULT NULL COMMENT '拨打电话的发起类型',
    customer VARCHAR(128) DEFAULT NULL COMMENT '联系人名称',
    customer_tel VARCHAR(32) DEFAULT NULL COMMENT '联系人电话',
    customer_id VARCHAR(32) DEFAULT NULL COMMENT '客户ID',
    dept_id BIGINT DEFAULT NULL COMMENT '用户所属组织机构ID',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '用户所属组织机构ID全路径',
    dept_info LONGTEXT COMMENT '用户所属组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '生成数据的设备的唯一标识',
    direction INT DEFAULT NULL COMMENT '通话类型',
    duration INT DEFAULT NULL COMMENT '通话时长',
    end_time VARCHAR(32) DEFAULT NULL COMMENT '电话挂断时间',
    end_timestamp BIGINT DEFAULT NULL COMMENT '挂断时间戳',
    iccid VARCHAR(64) DEFAULT NULL COMMENT '通话关联本机sim卡 iccid',
    iccid_phone VARCHAR(32) DEFAULT NULL COMMENT '通话关联本机sim卡手机号码',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    insert_time VARCHAR(13) DEFAULT NULL COMMENT '数据生成时的时间戳',
    is_connected INT DEFAULT NULL COMMENT '接通状态',
    mobile_vendor INT DEFAULT NULL COMMENT '本机运营商',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    phone_location VARCHAR(64) DEFAULT NULL COMMENT '联系人号码归属地',
    record VARCHAR(1024) DEFAULT NULL COMMENT '通话录音文件',
    req_id VARCHAR(64) DEFAULT NULL COMMENT '发起拨打电话请求的唯一标识',
    ring_duration INT DEFAULT NULL COMMENT '振铃时长',
    sound_channel INT DEFAULT NULL COMMENT '设备录音声道信息',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    timestamp BIGINT DEFAULT NULL COMMENT '时间戳',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户账号',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (es_id),
    KEY idx_mmba_call_customer_begin_ts (customer_id, begin_timestamp),
    KEY idx_mmba_call_customer_tel (customer_tel),
    KEY idx_mmba_call_um_begin_ts (um, begin_timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA通话审计表';

CREATE TABLE IF NOT EXISTS mmba_sms_record_audit (
    es_id VARCHAR(64) NOT NULL COMMENT '记录唯一标识',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    biz_ext_info LONGTEXT COMMENT '扩展字段',
    card_slot_num INT DEFAULT NULL COMMENT '发送接收卡槽号',
    content LONGTEXT COMMENT '信息内容',
    create_time VARCHAR(32) DEFAULT NULL COMMENT '发送时间',
    customer VARCHAR(128) DEFAULT NULL COMMENT '联系人名称',
    customer_tel VARCHAR(32) DEFAULT NULL COMMENT '联系人电话',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    direction INT DEFAULT NULL COMMENT '行为类型',
    iccid VARCHAR(64) DEFAULT NULL COMMENT '短信或彩信关联sim的iccid',
    iccid_phone VARCHAR(32) DEFAULT NULL COMMENT 'sim卡手机号',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    insert_time VARCHAR(13) DEFAULT NULL COMMENT '数据生成时的时间戳',
    net_sms BIT(1) DEFAULT NULL COMMENT '是否为5G短信',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    req_id VARCHAR(64) DEFAULT NULL COMMENT '业务id',
    sent_status INT DEFAULT NULL COMMENT '送达状态',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    subject VARCHAR(255) DEFAULT NULL COMMENT '彩信主题',
    timestamp BIGINT DEFAULT NULL COMMENT '字段createTime对应时间的时间戳',
    type INT DEFAULT NULL COMMENT '信息类型',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (es_id),
    KEY idx_mmba_sms_customer_tel (customer_tel),
    KEY idx_mmba_sms_um_timestamp (um, timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA短信审计表';

CREATE TABLE IF NOT EXISTS mmba_wx_account_audit (
    es_id VARCHAR(64) NOT NULL COMMENT '记录唯一标识',
    app_id BIGINT DEFAULT NULL COMMENT '应用ID',
    app_name VARCHAR(128) DEFAULT NULL COMMENT '应用名称',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    create_time VARCHAR(32) DEFAULT NULL COMMENT '数据产生时间',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    insert_time VARCHAR(13) DEFAULT NULL COMMENT '数据产生时间戳',
    note VARCHAR(255) DEFAULT NULL COMMENT '备注',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    qq VARCHAR(64) DEFAULT NULL COMMENT '微信绑定的QQ号',
    sign VARCHAR(255) DEFAULT NULL COMMENT '个性签名',
    staff_area VARCHAR(255) DEFAULT NULL COMMENT '地区',
    staff_id_in_app VARCHAR(128) DEFAULT NULL COMMENT '业务员微信账号ID',
    staff_im_app_account VARCHAR(128) DEFAULT NULL COMMENT '业务员微信登录账号',
    staff_im_app_header_pic LONGTEXT COMMENT '业务员微信账号图像',
    staff_im_nick_name VARCHAR(128) DEFAULT NULL COMMENT '业务员微信账号昵称',
    staff_mobile VARCHAR(32) DEFAULT NULL COMMENT '业务员微信账号手机号',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    staff_sex INT DEFAULT NULL COMMENT '业务员微信账号性别',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    timestamp BIGINT DEFAULT NULL COMMENT '字段createTime对应时间的时间戳',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    verified_status INT DEFAULT NULL COMMENT '是否实名认证',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (es_id),
    KEY idx_mmba_wx_account_um (um),
    KEY idx_mmba_wx_account_staff_id (staff_id_in_app)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA微信账号审计表';

CREATE TABLE IF NOT EXISTS mmba_wx_chat_audit (
    es_id VARCHAR(64) NOT NULL COMMENT '记录唯一标识',
    app_name VARCHAR(128) DEFAULT NULL COMMENT '应用名称',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    chat_sources_type INT DEFAULT NULL COMMENT '消息来源类型',
    chat_type INT DEFAULT NULL COMMENT '聊天内容类型',
    contact_description VARCHAR(1024) DEFAULT NULL COMMENT '联系人描述信息',
    content LONGTEXT COMMENT '微信聊天内容',
    customer VARCHAR(1024) DEFAULT NULL COMMENT '客户好友的备注',
    customer_account TEXT COMMENT '客户微信号',
    customer_account_id TEXT COMMENT '客户微信ID',
    customer_nickname VARCHAR(128) DEFAULT NULL COMMENT '客户微信昵称',
    customer_pic LONGTEXT COMMENT '客户微信头像',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    direction INT DEFAULT NULL COMMENT '聊天信息行为',
    duration VARCHAR(32) DEFAULT NULL COMMENT '语音视频消息时长',
    file_identifier VARCHAR(512) DEFAULT NULL COMMENT '文件标识',
    file_name VARCHAR(256) DEFAULT NULL COMMENT '真实文件名',
    friend_phone VARCHAR(32) DEFAULT NULL COMMENT '好友手机号',
    friend_search VARCHAR(32) DEFAULT NULL COMMENT '搜索内容',
    group_id VARCHAR(128) DEFAULT NULL COMMENT '群ID',
    group_name VARCHAR(128) DEFAULT NULL COMMENT '群名称',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    insert_time VARCHAR(13) DEFAULT NULL COMMENT '数据产生时间戳',
    member_account TEXT COMMENT '群内发言人微信ID',
    member_nick_name VARCHAR(128) DEFAULT NULL COMMENT '群内发言人昵称',
    member_pic LONGTEXT COMMENT '群内发言人头像',
    msg_id VARCHAR(128) DEFAULT NULL COMMENT '消息ID',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    quote_id VARCHAR(128) DEFAULT NULL COMMENT '引用ID',
    req_id VARCHAR(64) DEFAULT NULL COMMENT '业务id',
    staff_account TEXT COMMENT '业务员微信账号',
    staff_account_id TEXT COMMENT '业务员微信ID',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    staff_nickname VARCHAR(128) DEFAULT NULL COMMENT '业务员微信昵称',
    staff_pic LONGTEXT COMMENT '业务员微信头像',
    status INT DEFAULT NULL COMMENT '聊天收发状态',
    target_type INT DEFAULT NULL COMMENT '聊天对象类型',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    time VARCHAR(32) DEFAULT NULL COMMENT '微信聊天时间',
    timestamp BIGINT DEFAULT NULL COMMENT '微信聊天时间戳',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    contact_mobile VARCHAR(128) DEFAULT NULL COMMENT '好友手机号',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (es_id),
    KEY idx_mmba_wx_chat_req_id (req_id),
    KEY idx_mmba_wx_chat_customer_account_id (customer_account_id(255)),
    KEY idx_mmba_wx_chat_friend_phone (friend_phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA微信聊天审计表';

CREATE TABLE IF NOT EXISTS mmba_wx_friend_change_audit (
    es_id VARCHAR(64) NOT NULL COMMENT '记录唯一标识',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    contact_area VARCHAR(128) DEFAULT NULL COMMENT '地区',
    contac_im_app_note VARCHAR(64) DEFAULT NULL COMMENT '好友备注旧字段',
    contact_description VARCHAR(1024) DEFAULT NULL COMMENT '好友描述',
    contact_im_app_account TEXT COMMENT '好友微信号',
    contact_im_app_header_pic LONGTEXT COMMENT '头像',
    contact_im_app_nick_name VARCHAR(128) DEFAULT NULL COMMENT '好友微信昵称',
    contact_im_app_note VARCHAR(64) DEFAULT NULL COMMENT '好友备注',
    contact_im_id_in_app TEXT COMMENT '好友微信id',
    contact_mobile VARCHAR(255) DEFAULT NULL COMMENT '好友手机号',
    contact_sex VARCHAR(32) DEFAULT NULL COMMENT '性别',
    contact_weixin_tags VARCHAR(255) DEFAULT NULL COMMENT '好友标签ID',
    create_time VARCHAR(32) DEFAULT NULL COMMENT '记录产生时间',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    friend_phone VARCHAR(32) DEFAULT NULL COMMENT '微信朋友手机号',
    friend_search VARCHAR(32) DEFAULT NULL COMMENT 'API添加好友时搜索的内容',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    insert_time VARCHAR(13) DEFAULT NULL COMMENT '审计系统处理时的时间戳',
    is_friend VARCHAR(32) DEFAULT NULL COMMENT '好友类型',
    oper_flag INT DEFAULT NULL COMMENT '操作类型',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    source VARCHAR(32) DEFAULT NULL COMMENT '添加来源',
    staff_id_in_app VARCHAR(128) DEFAULT NULL COMMENT '自己微信id',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    timestamp BIGINT DEFAULT NULL COMMENT '字段createTime对应时间的时间戳',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    wx_type VARCHAR(32) DEFAULT NULL COMMENT '添加好友添加方式',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (es_id),
    KEY idx_mmba_wx_friend_change_contact_id (contact_im_id_in_app(255)),
    KEY idx_mmba_wx_friend_change_friend_phone (friend_phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA微信好友变更审计表';

CREATE TABLE IF NOT EXISTS mmba_wx_friend_list_audit (
    es_id VARCHAR(64) NOT NULL COMMENT '记录唯一标识',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    contac_im_app_note VARCHAR(64) DEFAULT NULL COMMENT '好友备注旧字段',
    contact_area VARCHAR(128) DEFAULT NULL COMMENT '地区',
    contact_description VARCHAR(1024) DEFAULT NULL COMMENT '好友描述',
    contact_im_app_account TEXT COMMENT '好友微信号',
    contact_im_app_header_pic LONGTEXT COMMENT '头像',
    contact_im_app_nick_name VARCHAR(128) DEFAULT NULL COMMENT '好友微信昵称',
    contact_im_app_note VARCHAR(64) DEFAULT NULL COMMENT '好友备注',
    contact_im_id_in_app TEXT COMMENT '好友微信id',
    contact_mobile VARCHAR(255) DEFAULT NULL COMMENT '好友手机号',
    contact_sex VARCHAR(32) DEFAULT NULL COMMENT '性别',
    contact_weixin_tags VARCHAR(255) DEFAULT NULL COMMENT '好友标签ID',
    create_time VARCHAR(32) DEFAULT NULL COMMENT '记录产生时间',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    insert_time VARCHAR(13) DEFAULT NULL COMMENT '数据产生时间戳',
    is_friend VARCHAR(32) DEFAULT NULL COMMENT '好友类型',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    staff_id_in_app VARCHAR(128) DEFAULT NULL COMMENT '自己微信id',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    timestamp BIGINT DEFAULT NULL COMMENT '字段createTime对应时间的时间戳',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (es_id),
    KEY idx_mmba_wx_friend_list_contact_id (contact_im_id_in_app(255)),
    KEY idx_mmba_wx_friend_list_contact_mobile (contact_mobile(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA微信好友列表审计表';

CREATE TABLE IF NOT EXISTS mmba_wx_login_audit (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    app_pkg_name VARCHAR(128) NOT NULL COMMENT '应用包名',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    create_time BIGINT NOT NULL COMMENT '数据产生时间',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    device_name VARCHAR(128) DEFAULT NULL COMMENT '产生数据的设备的名称',
    login_status INT DEFAULT NULL COMMENT '登录登出状态',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    staff_id_in_app VARCHAR(128) DEFAULT NULL COMMENT '业务员微信QQ账号ID',
    staff_im_app_account VARCHAR(128) DEFAULT NULL COMMENT '业务员微信QQ登录账号',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_wx_login_audit (app_pkg_name, staff_id_in_app, create_time),
    KEY idx_mmba_wx_login_um_time (um, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA登录登出审计表';

CREATE TABLE IF NOT EXISTS mmba_device_info_audit (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    change_time VARCHAR(32) DEFAULT NULL COMMENT '设备信息变更时间',
    dept_id BIGINT DEFAULT NULL COMMENT '当前组织机构id',
    dept_id_path VARCHAR(1024) DEFAULT NULL COMMENT '当前组织机构全路径',
    dept_info LONGTEXT COMMENT '当前组织机构信息',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '产生数据的设备的唯一标识',
    device_type VARCHAR(128) DEFAULT NULL COMMENT '设备型号',
    iccid VARCHAR(64) DEFAULT NULL COMMENT '卡槽1的sim卡标识',
    iccid2 VARCHAR(64) DEFAULT NULL COMMENT '卡槽2的sim卡标识',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    org_name VARCHAR(128) DEFAULT NULL COMMENT '用户所属组织机构名称',
    org_names VARCHAR(1024) DEFAULT NULL COMMENT '组织机构全路径',
    phone VARCHAR(32) DEFAULT NULL COMMENT '卡槽1的sim卡手机号',
    phone2 VARCHAR(32) DEFAULT NULL COMMENT '卡槽2的sim卡手机号',
    staff_name VARCHAR(128) DEFAULT NULL COMMENT '用户名称',
    telecom_operators VARCHAR(64) DEFAULT NULL COMMENT '卡槽1的sim卡运营商',
    telecom_operators2 VARCHAR(64) DEFAULT NULL COMMENT '卡槽2的sim卡运营商',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    timestamp BIGINT DEFAULT NULL COMMENT 'changeTime对应时间的时间戳',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_device_info_audit (device_id, imei, timestamp),
    KEY idx_mmba_device_info_imei (imei)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA设备信息审计表';

CREATE TABLE IF NOT EXISTS mmba_device_status_audit (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    behavior_type INT DEFAULT NULL COMMENT '审计类型',
    change_time VARCHAR(32) DEFAULT NULL COMMENT '事件完成时间',
    device_id VARCHAR(64) NOT NULL COMMENT '产生数据的设备的唯一标识',
    device_status INT DEFAULT NULL COMMENT '设备变化状态',
    imei VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性',
    imei2 VARCHAR(64) DEFAULT NULL COMMENT '设备自带的唯一标识属性2',
    tenancy_name VARCHAR(64) DEFAULT NULL COMMENT '公司code',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户登录名',
    raw_data LONGTEXT COMMENT '原始单条JSON',
    callback_record_id VARCHAR(32) DEFAULT NULL COMMENT '原始回调表ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mmba_device_status_audit (device_id, device_status, change_time),
    KEY idx_mmba_device_status_device_time (device_id, change_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA设备状态审计表';

CREATE TABLE IF NOT EXISTS mmba_media_file (
    id VARCHAR(32) NOT NULL COMMENT '主键ID',
    customer_id VARCHAR(32) DEFAULT NULL COMMENT '客户ID',
    audit_record_id VARCHAR(64) DEFAULT NULL COMMENT '关联审计记录ID',
    behavior_type INT DEFAULT NULL COMMENT '关联回调类型',
    req_id VARCHAR(64) DEFAULT NULL COMMENT '请求唯一标识',
    source_file_path VARCHAR(1024) DEFAULT NULL COMMENT 'MMBA源文件路径',
    source_type VARCHAR(64) DEFAULT NULL COMMENT '来源类型',
    download_status VARCHAR(32) DEFAULT NULL COMMENT '下载状态',
    retry_count INT DEFAULT 0 COMMENT '下载重试次数',
    last_download_time BIGINT DEFAULT NULL COMMENT '最后下载时间',
    error_message TEXT COMMENT '最后失败原因',
    storage_type VARCHAR(32) DEFAULT NULL COMMENT '存储类型',
    storage_path VARCHAR(1024) DEFAULT NULL COMMENT '存储路径',
    file_name VARCHAR(255) DEFAULT NULL COMMENT '文件名',
    file_ext VARCHAR(32) DEFAULT NULL COMMENT '后缀',
    mime_type VARCHAR(128) DEFAULT NULL COMMENT '媒体类型',
    file_size BIGINT DEFAULT NULL COMMENT '文件大小',
    md5 VARCHAR(64) DEFAULT NULL COMMENT '文件摘要',
    es_id VARCHAR(64) DEFAULT NULL COMMENT '关联审计记录ID',
    device_id VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    imei VARCHAR(64) DEFAULT NULL COMMENT 'IMEI',
    um VARCHAR(128) DEFAULT NULL COMMENT '用户名',
    raw_data LONGTEXT COMMENT '原始请求响应JSON',
    create_time BIGINT NOT NULL COMMENT '创建时间',
    create_user VARCHAR(32) NOT NULL COMMENT '创建人',
    update_time BIGINT NOT NULL COMMENT '更新时间',
    update_user VARCHAR(32) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    KEY idx_mmba_media_req_id (req_id),
    KEY idx_mmba_media_es_id (es_id),
    KEY idx_mmba_media_md5 (md5),
    KEY idx_mmba_media_es_source (es_id, source_file_path(255)),
    KEY idx_mmba_media_audit (behavior_type, audit_record_id),
    KEY idx_mmba_media_status_retry (download_status, retry_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='MMBA媒体文件元数据表';
